# render.yaml - Instruções de deploy para a plataforma Render

services:
  - type: web
    name: sisab-api
    env: python
    plan: free
    # Aumenta o tempo limite para o build, se necessário
    # buildTimeoutSeconds: 600
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn api_service.main:app --host 0.0.0.0 --port $PORT"
